create Table Jobs (
	ID int Identity(0,1),
	UID int null,
	Reference Varchar(max) null,
	SystemNum Varchar(max) null,
	CyclNumber Varchar(max) null,
	Dsc Varchar(max) null,
	Qty int null,
	Error varchar(max) null,
	Running int null,
	QtyWork int null,
	CustomerInfo varchar(max),
	JobCreationDate DateTime2 null,
	JobCompletedDate DateTime2 null,
	JobStartDate DateTime2 null,
	JobFinishDate DateTime2 null,
	Quantity int null,
	StatusCode varchar(max) null,
	BLA int null,
	BLB int null,
);